site_name: ""
site_description: Build language agents as graphs
site_url: https://langchain-ai.github.io/langgraph/
repo_url: https://github.com/langchain-ai/langgraph
edit_uri: edit/main/docs/docs/
theme:
  name: material
  custom_dir: overrides
  logo_dark_mode: static/wordmark_light.svg
  logo_light_mode: static/wordmark_dark.svg
  favicon: static/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.action.edit
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.tabs
    - navigation.footer
    # - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: white
      accent: gray
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Public Sans"
    code: "Roboto Mono"
  navigation:
    depth: 1
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - redirects:
      redirect_maps:
        'cloud/index.md': 'concepts/index.md#langgraph-platform'
        'cloud/how-tos/index.md': 'how-tos/index.md#langgraph-platform'
        'cloud/concepts/api.md': 'concepts/langgraph_server.md'
        'cloud/concepts/cloud.md': 'concepts/langgraph_cloud.md'
        'cloud/faq/studio.md': 'concepts/langgraph_studio.md#studio-faqs'
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://api.python.langchain.com/en/latest/objects.inv
          options:
            members_order: source
            allow_inspection: true
            heading_level: 2
            show_bases: true
            show_source: false 
            summary: true
            inherited_members: true
            selection:
              docstring_style: google
            docstring_section_style: list
            show_root_toc_entry: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            options:
              filters:
                - "!^_"
                -

extra_css:
  - stylesheets/hide_guides.css

nav:
  - Home:
    - Introduction: index.md
    - Get started:
      - Learn the basics: tutorials/introduction.ipynb
      - Deployment:
        - tutorials/deployment.md
        - Local Deploy: tutorials/langgraph-platform/local-server.md
        - Template Applications: concepts/template_applications.md  # TODO: make tutorial
        - Cloud Deploy: cloud/quick_start.md
    - Guides:
      - How-to guides: how-tos/index.md
      - Concepts:
        - concepts/index.md
        - LangGraph:
          - LangGraph: concepts#langgraph
          - concepts/high_level.md
          - concepts/low_level.md
          - concepts/agentic_concepts.md
          - concepts/multi_agent.md
          - concepts/breakpoints
          - concepts/human_in_the_loop.md
          - concepts/time-travel.md
          - concepts/persistence.md
          - concepts/memory.md
          - concepts/streaming.md
        - LangGraph Platform:
          - LangGraph Platform: concepts#langgraph-platform
          - High Level:
            - High Level: concepts#high-level
            - concepts/langgraph_platform.md
            - concepts/deployment_options.md
            - concepts/plans.md
            - concepts/template_applications.md
          - Components:
            - Components: concepts#components
            - concepts/langgraph_server.md
            - concepts/langgraph_studio.md
            - concepts/langgraph_cli.md
            - concepts/sdk.md
            - how-tos/use-remote-graph.md
          - LangGraph Server:
            - LangGraph Server: concepts#langgraph-server
            - concepts/application_structure.md
            - concepts/assistants.md
            - concepts/double_texting.md
            - concepts/auth.md
          - Deployment Options:
            - Deployment Options: concepts#deployment-options
            - concepts/self_hosted.md
            - concepts/langgraph_cloud.md
            - concepts/bring_your_own_cloud.md
      - Tutorials & Examples: tutorials/index.md
    - Resources:
      - FAQ: concepts/faq.md
      - Troubleshooting: troubleshooting/errors/index.md
      - LangGraph Academy Course: https://academy.langchain.com/courses/intro-to-langgraph
  
  - API reference:
    - LangGraph:
      - Graphs: reference/graphs.md
      - Checkpointing: reference/checkpoints.md
      - Storage: reference/store.md
      - Prebuilt components: reference/prebuilt.md
      - Channels: reference/channels.md
      - Errors: reference/errors.md
      - Types: reference/types.md
      - Constants: reference/constants.md
    - LangGraph Platform API:
      - Server API: "cloud/reference/api/api_ref.md"
      - CLI: "cloud/reference/cli.md"
      - SDK (Python): "cloud/reference/sdk/python_sdk_ref.md"
      - SDK (JS/TS): "cloud/reference/sdk/js_ts_sdk_ref.md"
      - RemoteGraph: reference/remote_graph.md
      - Environment variables: "cloud/reference/env_var.md"

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: langchain-ai
      repo: langgraph
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_include.include:
      base_path: ./
  - github-callouts
hooks:
  - _scripts/notebook_hooks.py
extra:
  social:
    - icon: fontawesome/brands/js
      link: https://langchain-ai.github.io/langgraphjs/
    - icon: fontawesome/brands/github
      link: https://github.com/langchain-ai/langgraph
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LangChainAI
  analytics:
    - provider: google
    - property: G-G8X6ELZYE0
    - feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Please help us improve this page by adding to the discussion below.
validation:
  # https://www.mkdocs.org/user-guide/configuration/
  # We're `ignoring` nav.omitted_files because we are going to rely
  # on files being properly links to from the index pages of:
  # - tutorials
  # - concepts
  # - how-tos
  # - reference
  omitted_files: ignore
  absolute_links: warn
  unrecognized_links: warn
  # TODO: figure out how to enable 'warn' for this
  # it's only an issue for tutorials/storm/storm.ipynb
  # because it creates anchors in the generated report
  # and those anchors are not available in the actual doc
  anchors: info
  # this is needed to handle headers with anchors for nav
  not_found: info
